services:
  - type: web
    name: AI-Job-Recruitment-Platform
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "8080"
