server:
  port: 8080

spring:
  application:
    name: talentflow-enterprise-platform
  datasource:
    url: jdbc:h2:mem:recruitmentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:recruitment-platform@demo.com}
    password: ${MAIL_PASSWORD:demopassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 hours
  upload:
    dir: ./uploads/resumes

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
